<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="desktop_leg">
    <xacro:macro name="add_desk_legs" params="name flag_x flag_y ground_desk_height desktop_length desktop_width">
        <link name="${name}_leg">
            <xacro:cylinder_inertial m="0.5" h="${ground_height - desktop_height/2}" r="0.05"/>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="0.05" length="${ground_height - desktop_height/2}"/>
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="0.05" length="${ground_height - desktop_height/2}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="${name}_leg">
            <material>
                Gazebo/Black
            </material>
        </gazebo>
        <joint name="${name}_leg2desk" type="fixed">
            <origin xyz="${(desktop_length/2-0.1) * flag_x} ${(desktop_width/2-0.1) * flag_y} ${- ground_height/2 - desktop_height/4}" rpy="0.0 0.0 0.0"/>
            <parent link="desk_square"/>
            <child link="${name}_leg"/>
        </joint>
    </xacro:macro>
</robot>